#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the rssaem usb connection."
echo ""

sudo cp `sudo cp `ros2 pkg prefix rssaem_bringup`/share/rssaem_bringup/script/99-rssaem-cdc.rules /etc/udev/rules.d/

echo ""
echo "Reload rules"
echo ""
sudo udevadm control --reload-rules
sudo udevadm trigger
